import { useState } from 'react';
import { buildBrief } from './coach.mjs';
export default function Coach({library,data,active,selected,onSelect,resolveExercise}) {
 const [question,setQuestion]=useState('');
 const [includeHistory,setIncludeHistory]=useState(true);
 const [message,setMessage]=useState('');
 const brief=buildBrief({data,active,selected,question,resolveExercise,includeHistory});
 const copy=async()=>{try{await navigator.clipboard.writeText(brief);setMessage('Brief copied. Open ChatGPT and paste it into your conversation.');}catch{setMessage('Clipboard unavailable. Select and copy the brief below.');}};
 return <div className="pad"><div className="eyebrow">COACH LINK / PERSONAL ACCOUNT</div><section className="coach-intro"><h2>YOUR TRAINING.<br/><span>A BETTER CONVERSATION.</span></h2><p>Bring the right context to your own ChatGPT chat. No API key needed.</p></section><div className="coach-steps"><span>01 PREPARE</span><span>02 COPY & ASK</span><span>03 REVIEW & TUNE</span></div><label className="field-label">FOCUS<select value={selected} onChange={e=>onSelect(e.target.value)}><option value="">Program / current session</option>{library.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label className="field-label">WHAT WOULD YOU LIKE TO KNOW?<textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Should I increase load? How do I set this up? What can I substitute?" rows={3}/></label><label className="share-check"><input type="checkbox" checked={includeHistory} onChange={e=>setIncludeHistory(e.target.checked)}/>Include recent logs, local targets and active sets</label><p className="hint">Nothing is sent automatically. Review the brief before sharing. Answers happen in ChatGPT under your account’s available plan and limits; they do not automatically change your program.</p><details className="brief-preview" open><summary>REVIEW YOUR BRIEF</summary><textarea aria-label="Training brief" readOnly value={brief} rows={9} onFocus={e=>e.target.select()}/></details><div className="coach-actions"><button className="cta" onClick={copy}>COPY TRAINING BRIEF</button><a className="secondary-link" href="https://chatgpt.com/" target="_blank" rel="noopener noreferrer">OPEN CHATGPT ↗</a></div><p role="status" className="vault-msg">{message}</p><div className="coach-note"><h3>HOW PROGRESSION WORKS</h3><p>Your local engine compares completed working sets, rep ranges and effort. ChatGPT can help explain or revise those targets. Apply decisions in BUILD, or enter the agreed load in your next session.</p><p>A deeper connection can expose workout tools to ChatGPT through a plugin. That requires a separate service and account setup; this browser app currently uses a manual handoff.</p></div></div>;
}
