const BASE_LIBRARY = [
  // SQUAT RACK / BARBELL
  { id: "back-squat", name: "Back Squat", eq: "RACK", mus: "QUADS", range: [5, 6], inc: 5, sets: 4, kind: "COMPOUND" },
  { id: "front-squat", name: "Front Squat", eq: "RACK", mus: "QUADS", range: [5, 8], inc: 5, sets: 3, kind: "COMPOUND" },
  { id: "paused-squat", name: "Paused Back Squat", eq: "RACK", mus: "QUADS", range: [6, 8], inc: 5, sets: 3, kind: "COMPOUND" },
  { id: "bench", name: "Bench Press", eq: "RACK", mus: "CHEST", range: [5, 6], inc: 5, sets: 4, kind: "COMPOUND" },
  { id: "bench-vol", name: "Bench Press — Volume", eq: "RACK", mus: "CHEST", range: [8, 10], inc: 5, sets: 3, kind: "COMPOUND" },
  { id: "ohp", name: "Standing Overhead Press", eq: "RACK", mus: "DELTS", range: [5, 8], inc: 5, sets: 4, kind: "COMPOUND" },
  { id: "ohp-vol", name: "Overhead Press — Volume", eq: "RACK", mus: "DELTS", range: [8, 10], inc: 5, sets: 3, kind: "COMPOUND" },
  { id: "bb-row", name: "Barbell Row", eq: "RACK", mus: "BACK", range: [6, 10], inc: 5, sets: 3, kind: "COMPOUND" },
  { id: "bb-rdl", name: "Barbell RDL", eq: "RACK", mus: "HAMS", range: [6, 10], inc: 10, sets: 3, kind: "COMPOUND" },
  { id: "incline-bench", name: "Incline Bench Press", eq: "RACK", mus: "CHEST", range: [6, 10], inc: 5, sets: 3, kind: "COMPOUND" },
  { id: "close-grip-bench", name: "Close-Grip Bench", eq: "RACK", mus: "TRICEPS", range: [6, 10], inc: 5, sets: 3, kind: "COMPOUND" },
  { id: "hip-thrust", name: "Barbell Hip Thrust", eq: "RACK", mus: "GLUTES", range: [8, 12], inc: 10, sets: 3, kind: "COMPOUND" },
  { id: "good-morning", name: "Good Morning", eq: "RACK", mus: "HAMS", range: [8, 10], inc: 5, sets: 3, kind: "COMPOUND" },
  { id: "rack-pull", name: "Rack Pull", eq: "RACK", mus: "BACK", range: [5, 8], inc: 10, sets: 3, kind: "COMPOUND" },
  { id: "bb-calf", name: "Standing Calf Raise (BB)", eq: "RACK", mus: "CALVES", range: [10, 15], inc: 10, sets: 3, kind: "ACCESSORY" },
  // OPEN HEX BAR
  { id: "trap-dl", name: "Trap-Bar Deadlift", eq: "HEX", mus: "HAMS", range: [4, 6], inc: 10, sets: 4, kind: "COMPOUND" },
  { id: "trap-rdl", name: "Trap-Bar RDL", eq: "HEX", mus: "HAMS", range: [6, 10], inc: 10, sets: 3, kind: "COMPOUND" },
  { id: "trap-carry", name: "Trap-Bar Carry", eq: "HEX", mus: "CORE", range: [30, 60], inc: 10, sets: 3, kind: "CARRY", unit: "sec" },
  { id: "trap-shrug", name: "Trap-Bar Shrug", eq: "HEX", mus: "BACK", range: [10, 15], inc: 10, sets: 3, kind: "ACCESSORY" },
  // ARCADIA — CABLES + PULL-UP BAR
  { id: "pullup", name: "Pull-Up", eq: "ARCADIA", mus: "LATS", range: [5, 10], inc: 5, sets: 3, kind: "COMPOUND", bw: true },
  { id: "chinup", name: "Chin-Up", eq: "ARCADIA", mus: "LATS", range: [5, 10], inc: 5, sets: 3, kind: "COMPOUND", bw: true },
  { id: "hanging-leg-raise", name: "Hanging Leg Raise", eq: "ARCADIA", mus: "CORE", range: [8, 15], inc: 0, sets: 3, kind: "CORE", bw: true },
  { id: "cable-crunch", name: "Cable Crunch", eq: "ARCADIA", mus: "CORE", range: [12, 15], inc: 5, sets: 3, kind: "CORE" },
  { id: "rear-delt-fly", name: "Cable Rear-Delt Fly", eq: "ARCADIA", mus: "DELTS", range: [12, 20], inc: 2.5, sets: 3, kind: "ACCESSORY" },
  { id: "lat-pulldown", name: "Kneeling Lat Pulldown", eq: "ARCADIA", mus: "LATS", range: [8, 12], inc: 5, sets: 3, kind: "ACCESSORY" },
  { id: "cable-row", name: "Standing Cable Row", eq: "ARCADIA", mus: "BACK", range: [8, 12], inc: 5, sets: 3, kind: "ACCESSORY" },
  { id: "seated-cable-row", name: "Seated Cable Row", eq: "ARCADIA", mus: "BACK", range: [10, 12], inc: 5, sets: 3, kind: "ACCESSORY" },
  { id: "cable-chest-press", name: "Cable Chest Press", eq: "ARCADIA", mus: "CHEST", range: [8, 12], inc: 5, sets: 3, kind: "ACCESSORY" },
  { id: "cable-fly", name: "Cable Fly", eq: "ARCADIA", mus: "CHEST", range: [12, 15], inc: 2.5, sets: 3, kind: "ACCESSORY" },
  { id: "face-pull", name: "Face Pull", eq: "ARCADIA", mus: "DELTS", range: [15, 20], inc: 2.5, sets: 2, kind: "ACCESSORY" },
  { id: "cable-lateral", name: "Cable Lateral Raise", eq: "ARCADIA", mus: "DELTS", range: [12, 20], inc: 2.5, sets: 3, kind: "ACCESSORY" },
  { id: "cable-curl", name: "Cable Curl", eq: "ARCADIA", mus: "BICEPS", range: [10, 12], inc: 2.5, sets: 3, kind: "ACCESSORY" },
  { id: "rope-pushdown", name: "Rope Pushdown", eq: "ARCADIA", mus: "TRICEPS", range: [12, 15], inc: 2.5, sets: 2, kind: "ACCESSORY" },
  { id: "oh-tricep", name: "Cable Overhead Tricep Ext.", eq: "ARCADIA", mus: "TRICEPS", range: [10, 12], inc: 2.5, sets: 3, kind: "ACCESSORY" },
  { id: "pallof", name: "Pallof Press", eq: "ARCADIA", mus: "CORE", range: [10, 12], inc: 2.5, sets: 2, kind: "CORE" },
  { id: "woodchop", name: "Cable Woodchop", eq: "ARCADIA", mus: "CORE", range: [10, 12], inc: 2.5, sets: 2, kind: "CORE" },
  { id: "cable-pullthrough", name: "Cable Pull-Through", eq: "ARCADIA", mus: "GLUTES", range: [12, 15], inc: 5, sets: 3, kind: "ACCESSORY" },
  // HYPER PRO + LEG DEVELOPER
  { id: "leg-ext", name: "Leg Extension", eq: "HYPER PRO", mus: "QUADS", range: [10, 15], inc: 5, sets: 3, kind: "ACCESSORY" },
  { id: "leg-curl", name: "Lying Hamstring Curl", eq: "HYPER PRO", mus: "HAMS", range: [10, 15], inc: 5, sets: 3, kind: "ACCESSORY" },
  { id: "back-ext", name: "Back Extension", eq: "HYPER PRO", mus: "ERECTORS", range: [10, 15], inc: 5, sets: 2, kind: "ACCESSORY" },
  { id: "reverse-hyper", name: "Reverse Hyper", eq: "HYPER PRO", mus: "GLUTES", range: [10, 15], inc: 5, sets: 2, kind: "ACCESSORY" },
  { id: "nordic", name: "Nordic Curl", eq: "HYPER PRO", mus: "HAMS", range: [4, 8], inc: 0, sets: 3, kind: "ACCESSORY", bw: true },
  { id: "ghd-situp", name: "GHD Sit-Up", eq: "HYPER PRO", mus: "CORE", range: [8, 15], inc: 0, sets: 2, kind: "CORE", bw: true },
  // ADJUSTABLE DUMBBELLS
  { id: "db-bench", name: "DB Bench Press", eq: "DUMBBELL", mus: "CHEST", range: [8, 12], inc: 5, sets: 3, kind: "ACCESSORY" },
  { id: "incline-db", name: "Incline DB Press", eq: "DUMBBELL", mus: "CHEST", range: [8, 12], inc: 5, sets: 3, kind: "ACCESSORY" },
  { id: "bss", name: "Bulgarian Split Squat", eq: "DUMBBELL", mus: "QUADS", range: [8, 10], inc: 5, sets: 3, kind: "ACCESSORY", perSide: true },
  { id: "goblet", name: "Goblet Squat", eq: "DUMBBELL", mus: "QUADS", range: [10, 15], inc: 5, sets: 3, kind: "ACCESSORY" },
  { id: "db-row", name: "One-Arm DB Row", eq: "DUMBBELL", mus: "BACK", range: [8, 12], inc: 5, sets: 3, kind: "ACCESSORY", perSide: true },
  { id: "db-rdl", name: "DB RDL", eq: "DUMBBELL", mus: "HAMS", range: [10, 12], inc: 5, sets: 3, kind: "ACCESSORY" },
  { id: "db-curl", name: "DB Curl", eq: "DUMBBELL", mus: "BICEPS", range: [10, 12], inc: 2.5, sets: 3, kind: "ACCESSORY" },
  { id: "hammer-curl", name: "Hammer Curl", eq: "DUMBBELL", mus: "BICEPS", range: [12, 15], inc: 2.5, sets: 2, kind: "ACCESSORY" },
  { id: "db-lateral", name: "DB Lateral Raise", eq: "DUMBBELL", mus: "DELTS", range: [12, 20], inc: 2.5, sets: 3, kind: "ACCESSORY" },
  { id: "db-ohp", name: "Seated DB Shoulder Press", eq: "DUMBBELL", mus: "DELTS", range: [8, 12], inc: 5, sets: 3, kind: "ACCESSORY" },
  { id: "db-lunge", name: "DB Walking Lunge", eq: "DUMBBELL", mus: "QUADS", range: [8, 12], inc: 5, sets: 3, kind: "ACCESSORY", perSide: true },
  { id: "db-stepup", name: "DB Step-Up", eq: "DUMBBELL", mus: "GLUTES", range: [8, 12], inc: 5, sets: 3, kind: "ACCESSORY", perSide: true },
  { id: "db-calf", name: "Single-Leg DB Calf Raise", eq: "DUMBBELL", mus: "CALVES", range: [10, 15], inc: 5, sets: 3, kind: "ACCESSORY", perSide: true },
  { id: "db-pullover", name: "DB Pullover", eq: "DUMBBELL", mus: "LATS", range: [10, 12], inc: 5, sets: 3, kind: "ACCESSORY" },
];

export { BASE_LIBRARY };
