import { BASE_LIBRARY } from './exercises.mjs';
export const EQUIPMENT = ['RACK', 'HEX', 'ARCADIA', 'HYPER PRO', 'DUMBBELL'];
// Each variation has a distinct log identity; optional attachments are explicit.
const rows = [
['RACK','QUADS','bb-split-squat','Barbell Split Squat','Use rack safeties. Set a stationary split stance; lower vertically.',true],
['RACK','QUADS','bb-reverse-lunge','Barbell Reverse Lunge','Unrack with room behind you; step back softly and drive through the front foot.',true],
['RACK','QUADS','tempo-squat','Tempo Back Squat','Use safeties. Lower for three seconds; keep the same depth each rep.'],
['RACK','QUADS','pin-squat','Pin Squat','Set both safety pins to a comfortable depth; settle the bar without collapsing.'],
['RACK','CHEST','pause-bench','Paused Bench Press','Use a stable flat bench and safeties; pause lightly on the chest without bouncing.'],
['RACK','CHEST','bb-floor-press','Barbell Floor Press','Set rack hooks for a floor start; pause upper arms gently on the floor.'],
['RACK','CHEST','spoto-press','Spoto Press','Use a flat bench and safeties; stop just above the chest and pause.'],
['RACK','BACK','pendlay-row','Pendlay Row','Start each rep from the floor; brace with a stable torso and avoid jerking.'],
['RACK','BACK','underhand-row','Underhand Barbell Row','Hinge at the hips with palms forward; pull toward the lower ribs.'],
['RACK','HAMS','conventional-dl','Conventional Deadlift','Start with the bar over midfoot; brace, keep it close, and stand without leaning back.'],
['RACK','GLUTES','sumo-dl','Sumo Deadlift','Use a comfortable wide stance; knees track toes as you push the floor away.'],
['RACK','GLUTES','bb-glute-bridge','Barbell Floor Glute Bridge','Pad the bar across the hips; keep ribs down and stop at hip extension.'],
['RACK','BICEPS','bb-curl','Barbell Curl','Stand tall with elbows near your sides; curl without swinging.'],
['RACK','BICEPS','bb-reverse-curl','Barbell Reverse Curl','Use a palms-down grip and light load; keep wrists neutral.'],
['RACK','TRICEPS','bb-skullcrusher','Barbell Lying Triceps Extension','Use a flat bench and light bar; bend the elbows under control with a secure grip.'],
['RACK','BACK','bb-shrug','Barbell Shrug','Stand tall and lift shoulders straight up; avoid rolling them.'],
['HEX','QUADS','hex-high-dl','High-Handle Hex Deadlift','Requires high handles. Brace inside the bar; push evenly through both feet.'],
['HEX','HAMS','hex-low-dl','Low-Handle Hex Deadlift','Use low handles only within a controlled range; keep the spine stable.'],
['HEX','HAMS','hex-pause-dl','Paused Hex Deadlift','Pause just off the floor while maintaining your brace; reset each rep.'],
['HEX','QUADS','hex-split-squat','Open Hex Split Squat','Use the open side for leg clearance; check frame clearance before loading.',true],
['HEX','QUADS','hex-reverse-lunge','Open Hex Reverse Lunge','Confirm rear-leg clearance with an empty bar; step back under control.',true],
['HEX','CORE','hex-hold','Hex Bar Static Hold','Stand tall inside the bar with space to set it down; breathe behind a firm brace.',false,'sec'],
['HEX','BACK','hex-row','Hex Bar Bent-Over Row','Check frame clearance first; hinge and pull with a stable torso.'],
['ARCADIA','LATS','sa-pulldown','Single-Arm Kneeling Pulldown','Use a high pulley and single handle; kneel securely and pull elbow toward hip.',true],
['ARCADIA','LATS','straight-arm-pulldown','Straight-Arm Cable Pulldown','Use a high pulley and compatible bar or rope; sweep toward thighs without arching.'],
['ARCADIA','BACK','sa-cable-row','Single-Arm Cable Row','Set a handle at lower-chest height; row without rotating the torso.',true],
['ARCADIA','BACK','high-cable-row','High Cable Row','Set handles above shoulder height; pull elbows down and back.'],
['ARCADIA','BACK','kneeling-cable-row','Half-Kneeling Cable Row','Use one handle; squeeze the rear glute and keep hips square.',true],
['ARCADIA','CHEST','sa-cable-press','Single-Arm Cable Chest Press','Use a staggered stance and chest-height handle; resist torso rotation.',true],
['ARCADIA','CHEST','low-high-fly','Low-to-High Cable Fly','Start handles low; sweep upward with softly bent elbows.'],
['ARCADIA','CHEST','high-low-fly','High-to-Low Cable Fly','Start handles high; bring hands down and together without shrugging.'],
['ARCADIA','CHEST','sa-cable-fly','Single-Arm Cable Fly','Set a chest-height handle; keep the elbow angle steady through the arc.',true],
['ARCADIA','DELTS','cable-front-raise','Cable Front Raise','Use a low handle; raise to shoulder height without leaning back.'],
['ARCADIA','DELTS','cable-y-raise','Cable Y Raise','Use light low-pulley handles; lift in a Y with ribs down.'],
['ARCADIA','DELTS','cable-external-rotation','Cable External Rotation','Set a light handle at elbow height; keep elbow tucked and rotate outward.',true],
['ARCADIA','DELTS','sa-rear-fly','Single-Arm Cable Rear Fly','Use a shoulder-height handle across the body; open without twisting.',true],
['ARCADIA','BICEPS','sa-cable-curl','Single-Arm Cable Curl','Use one low handle; keep your elbow beside your torso.',true],
['ARCADIA','BICEPS','bayesian-curl','Behind-Body Cable Curl','Stand ahead of a low pulley; allow a comfortable shoulder position and curl.',true],
['ARCADIA','BICEPS','rope-hammer-curl','Rope Hammer Curl','Requires rope attachment. Keep palms facing inward and upper arms still.'],
['ARCADIA','BICEPS','high-cable-curl','High Cable Curl','Use high handles; curl toward the sides of your head without shrugging.'],
['ARCADIA','TRICEPS','sa-pushdown','Single-Arm Cable Pushdown','Use one high handle; extend the elbow without moving the shoulder.',true],
['ARCADIA','TRICEPS','cross-body-ext','Cross-Body Cable Triceps Extension','Use a high handle across your chest; extend one elbow with control.',true],
['ARCADIA','TRICEPS','sa-overhead-ext','Single-Arm Overhead Cable Extension','Use one handle behind you; keep ribs down and a comfortable elbow path.',true],
['ARCADIA','CORE','pallof-hold','Pallof Isometric Hold','Use a chest-height handle; hold arms extended while resisting rotation.',true,'sec'],
['ARCADIA','CORE','low-high-chop','Low-to-High Cable Chop','Use a low handle; move diagonally with controlled hips and torso.',true],
['ARCADIA','CORE','kneeling-pallof','Tall-Kneeling Pallof Press','Kneel side-on to a chest-height pulley; keep hips extended as arms press out.',true],
['ARCADIA','CORE','hanging-knee','Hanging Knee Raise','Use the pull-up bar; raise bent knees without swinging.',false,'reps',true],
['ARCADIA','LATS','scap-pullup','Scapular Pull-Up','Hang from the pull-up bar; keep arms straight and draw shoulders down.',false,'reps',true],
['ARCADIA','LATS','eccentric-pullup','Eccentric Pull-Up','Requires a stable step to reach the top. Lower under control; do not jump to a high bar.',false,'reps',true],
['HYPER PRO','HAMS','nordic-eccentric','Eccentric Nordic Curl','Lock the machine in Nordic mode; lower within control and use hands to return.',false,'reps',true],
['HYPER PRO','HAMS','nordic-partial','Partial-Range Nordic Curl','Use the manufacturer Nordic setup; choose a repeatable shallow range.',false,'reps',true],
['HYPER PRO','HAMS','sl-leg-curl','Single-Leg Hamstring Curl','Requires leg developer. Align knee with pivot and use light load.',true],
['HYPER PRO','QUADS','sl-leg-ext','Single-Leg Leg Extension','Requires leg developer. Align the knee pivot and extend without kicking.',true],
['HYPER PRO','GLUTES','glute-back-ext','Glute-Focused Back Extension','Set hip pad below the hip crease; extend through the hips and stop at body alignment.'],
['HYPER PRO','ERECTORS','back-ext-hold','Back Extension Isometric Hold','Secure feet in back-extension mode; hold a neutral body line.',false,'sec',true],
['HYPER PRO','CORE','hyper-side-bend','Hyper Pro Side Bend','Use only the manufacturer side-bend setup with secure foot support; move slowly.',true],
['HYPER PRO','CORE','ghd-crunch','Short-Range GHD Crunch','Use a secure GHD setup and shallow range; avoid dropping into deep extension.',false,'reps',true],
['DUMBBELL','CHEST','db-floor','DB Floor Press','Lie on the floor; pause upper arms lightly before pressing.'],
['DUMBBELL','CHEST','db-neutral-press','Neutral-Grip DB Bench Press','Requires flat bench. Keep palms facing and forearms vertical.'],
['DUMBBELL','CHEST','db-squeeze','DB Squeeze Press','Requires flat bench. Hold dumbbells together over the chest and press.'],
['DUMBBELL','CHEST','db-fly','DB Chest Fly','Requires flat bench. Use light load and a comfortable arc with softly bent elbows.'],
['DUMBBELL','DELTS','db-standing-press','Standing DB Shoulder Press','Brace with ribs down; press overhead without leaning back.'],
['DUMBBELL','DELTS','db-arnold','Arnold Press','Use a stable seat or standing stance; rotate only through a comfortable range.'],
['DUMBBELL','DELTS','db-rear-fly','Bent-Over DB Reverse Fly','Hinge with a stable torso; lift arms wide without shrugging.'],
['DUMBBELL','DELTS','db-front-raise','DB Front Raise','Stand tall; raise to shoulder height without swinging.'],
['DUMBBELL','BACK','db-supported-row','Chest-Supported DB Row','Requires incline bench. Keep chest supported and pull toward your ribs.'],
['DUMBBELL','BACK','db-shrug','DB Shrug','Stand tall; raise shoulders vertically and lower slowly.'],
['DUMBBELL','HAMS','db-sl-rdl','Single-Leg DB RDL','Hinge on one leg with hips square; use light load and a stable reach.',true],
['DUMBBELL','HAMS','db-kickstand-rdl','Kickstand DB RDL','Use the rear foot as light support; hinge over the front leg.',true],
['DUMBBELL','QUADS','db-reverse-lunge','DB Reverse Lunge','Step backward softly; drive through the planted front foot.',true],
['DUMBBELL','QUADS','db-split-squat','DB Split Squat','Hold a fixed split stance and lower under control.',true],
['DUMBBELL','QUADS','db-front-squat','Double DB Front Squat','Hold dumbbells at shoulders; brace and squat to a controlled depth.'],
['DUMBBELL','GLUTES','db-glute-bridge','DB Glute Bridge','Rest a secured dumbbell across the hips; extend without arching the back.'],
['DUMBBELL','BICEPS','db-incline-curl','Incline DB Curl','Requires incline bench. Let arms hang and curl without swinging.'],
['DUMBBELL','BICEPS','db-concentration','Concentration Curl','Sit securely with elbow against inner thigh; curl slowly.',true],
['DUMBBELL','BICEPS','db-cross-hammer','Cross-Body Hammer Curl','Keep a neutral grip; curl toward the opposite shoulder.',true],
['DUMBBELL','TRICEPS','db-overhead-ext','DB Overhead Triceps Extension','Secure the dumbbell with both hands; keep ribs down and bend elbows slowly.'],
['DUMBBELL','TRICEPS','db-skullcrusher','DB Floor Triceps Extension','Lie on the floor; bend elbows with neutral wrists and a secure grip.'],
['DUMBBELL','TRICEPS','db-kickback','DB Triceps Kickback','Hinge and keep upper arm still; straighten the elbow with a light weight.',true],
['DUMBBELL','CALVES','db-seated-calf','Seated DB Calf Raise','Sit securely, pad the dumbbells on thighs, and raise heels slowly.'],
['DUMBBELL','CORE','db-farmer','DB Farmer Carry','Use a clear walking route; keep shoulders level and take controlled steps.',false,'sec'],
['DUMBBELL','CORE','db-suitcase','DB Suitcase Carry','Carry one dumbbell without leaning; use a clear path.',true,'sec'],
['DUMBBELL','CORE','db-suitcase-hold','DB Suitcase Hold','Stand with one dumbbell; resist leaning and breathe steadily.',true,'sec'],
['DUMBBELL','CORE','db-deadbug','DB Dead Bug','Hold a light dumbbell above chest; alternate leg reaches while keeping back stable.',true],
];
const EXTRA = rows.map(([eq,mus,id,name,cue,perSide=false,unit='reps',bw=false]) => ({id,name,eq,mus,cue,perSide,unit,bw,range:unit==='sec'?[20,40]:id.includes('nordic')||id==='eccentric-pullup'?[3,6]:[8,12],inc:bw?0:eq==='ARCADIA'?2.5:5,sets:3,kind:unit==='sec'?'CARRY':mus==='CORE'?'CORE':'ACCESSORY'}));
export const LIB = [...BASE_LIBRARY, ...EXTRA];
export const LIB_MAP = Object.fromEntries(LIB.map(e=>[e.id,e]));
const setups = {
 RACK: 'Rack + barbell and plates. Bench variations also need a stable, appropriate bench. Set safeties before lifting.',
 HEX: 'Open hex bar + plates. Confirm handle and frame clearance with an unloaded rehearsal.',
 ARCADIA: 'REP Arcadia functional trainer. Use securely clipped compatible handles; rope/bar/cuff movements require that attachment.',
 'HYPER PRO': 'Freak Athlete Hyper Pro. Lock adjustments according to its manual; extensions and curls require the leg developer.',
 DUMBBELL: 'Adjustable dumbbells with locks fully engaged. Bench/step variations require a stable, load-rated bench or platform.'
};
export function guideFor(ex) { return {
 setup: setups[ex.eq],
 cue: ex.cue || `Use a controlled, comfortable range for ${ex.name.toLowerCase()}; avoid momentum and stop if the movement causes pain. ${ex.perSide?'Complete the target on each side.':''}`,
 load: ex.bw?'Log added load only; 0 lb means bodyweight.':ex.eq==='DUMBBELL'?'Log the weight of ONE dumbbell; keep that convention each session.':ex.eq==='ARCADIA'?'Log the selected stack weight per side, consistently. Pulley ratios mean this is not directly comparable to free weights.':'Log total external load consistently, including the bar when applicable.'
}; }
export function filterExercises(lib, eq='ALL', mus='ALL', query='') { const terms=query.toLowerCase().trim().split(/\s+/).filter(Boolean); return lib.filter(e=>(eq==='ALL'||e.eq===eq)&&(mus==='ALL'||e.mus===mus)&&terms.every(t=>`${e.name} ${e.eq} ${e.mus}`.toLowerCase().includes(t))); }
