export const FONT_FACES = `
@font-face{font-family:'Rajdhani';font-style:normal;font-weight:500;font-display:swap;src:url('./fonts/rajdhani-500.ttf') format('truetype')}
@font-face{font-family:'Rajdhani';font-style:normal;font-weight:600;font-display:swap;src:url('./fonts/rajdhani-600.ttf') format('truetype')}
@font-face{font-family:'Rajdhani';font-style:normal;font-weight:700;font-display:swap;src:url('./fonts/rajdhani-700.ttf') format('truetype')}
@font-face{font-family:'Share Tech Mono';font-style:normal;font-weight:400;font-display:swap;src:url('./fonts/share-tech-mono.ttf') format('truetype')}
`;

// Extend the original compact Night City interface; base glow and typography live in CyberTrain.jsx.
export const EX_THEME = `
:root{color-scheme:dark;--yellow:#fcee0a;--cyan:#00f0ff;--muted:#8490a8;--frame:620px;--ease:cubic-bezier(.22,1,.36,1)}
html,body,#root{height:100%;overflow:hidden;background:#04050b}
body{background:radial-gradient(ellipse at 35% 20%,#00f0ff09,transparent 45%),radial-gradient(ellipse at 70% 80%,#ff2a6d0b,transparent 50%),#04050b}
.ct-root,.ct-root.resting{width:100%;max-width:var(--frame);height:100dvh;min-height:0;margin:0 auto;padding:0;display:flex;flex-direction:column;overflow:hidden;isolation:isolate;background-color:#07080f;background-image:radial-gradient(ellipse at 20% 0%,#00f0ff0d,transparent 55%),radial-gradient(ellipse at 100% 90%,#ff2a6d0b,transparent 65%);font-weight:500}
.scanlines{position:absolute;z-index:8;opacity:.65;background:repeating-linear-gradient(0deg,#0002 0 1px,transparent 1px 4px)}
.hdr{flex-shrink:0;padding:calc(19px + env(safe-area-inset-top)) 18px 15px;background:linear-gradient(115deg,#0d1220e6,#07080fee);z-index:10;border-bottom-color:#00f0ff2b}
.hdr::after{left:18px;width:74px;box-shadow:0 0 8px #fcee0a,0 0 24px #fcee0a70}
.hdr h1{font-size:28px;letter-spacing:.7px}.hdr h1 em{display:inline-block;vertical-align:top;font:9px 'Share Tech Mono',monospace;font-style:normal;color:#00f0ff;border:1px solid #00f0ff66;background:#00f0ff0d;padding:3px 4px;margin-left:7px;margin-top:1px;box-shadow:0 0 12px #00f0ff20;text-shadow:0 0 8px #00f0ff99}
.hdr-sub{font-size:8px;letter-spacing:.14em;color:#8591a8;margin-top:5px}.hdr-stat-l{color:#8591a8}.hdr-stat-n{font-variant-numeric:tabular-nums}
.system-strip{flex-shrink:0;display:flex;justify-content:space-between;align-items:center;padding:9px 18px;font:8px 'Share Tech Mono',monospace;letter-spacing:.09em;color:#7b869c;border-bottom:1px solid #ffffff06;background:#080c15;z-index:9}.system-strip span:first-child{color:#62c7ce}.system-strip i{display:inline-block;width:4px;height:4px;background:#00f0ff;box-shadow:0 0 7px #00f0ff;margin:0 5px 1px 0}.system-strip b{font-weight:400;color:#3b4b60;padding:0 4px}
.main{width:100%;max-width:none;min-height:0;flex:1;overflow-y:auto;overflow-x:hidden;overscroll-behavior-y:contain;scrollbar-width:thin;scrollbar-color:#26354a transparent;scroll-padding-block:14px;-webkit-overflow-scrolling:touch}
.pad{padding:19px 16px 24px}.training-readout{display:flex;align-items:center;justify-content:space-between;padding-bottom:14px;margin-bottom:20px;border-bottom:1px dashed #00f0ff24;font:9px 'Share Tech Mono',monospace;letter-spacing:.12em;color:#69778e}.training-readout span:first-child{color:#c1ccdd}.section-heading{display:flex;align-items:baseline;justify-content:space-between}.section-heading>span{font:9px 'Share Tech Mono',monospace;color:#586980}.sec-label{font-size:10px;margin-bottom:13px}
.day-slot{--dc:#fcee0a;margin-bottom:11px;transition:filter .24s var(--ease);filter:drop-shadow(0 2px 5px #0006)}.day-slot.selected{filter:drop-shadow(0 0 7px color-mix(in srgb,var(--dc) 18%,transparent))}
.day-card{position:relative;min-height:77px;margin:0;padding:16px 14px;gap:13px;background:linear-gradient(115deg,#111628,#0b0e1a);border:1px solid #ffffff12;transition:background .2s,border-color .2s,transform .18s var(--ease),box-shadow .2s;text-wrap:pretty}
.day-card::before{content:'';position:absolute;left:0;top:0;bottom:0;width:2px;background:var(--dc);opacity:.4;box-shadow:0 0 10px var(--dc)}
.day-card.sel{border-color:color-mix(in srgb,var(--dc) 72%,transparent);background:linear-gradient(110deg,color-mix(in srgb,var(--dc) 7%,#101523),#0d101e 78%);box-shadow:inset 0 0 26px color-mix(in srgb,var(--dc) 5%,transparent)}.day-card.sel::before{opacity:1}
.day-letter{font-size:31px;flex-shrink:0;width:30px;line-height:1}.day-name{font-size:16px;letter-spacing:.045em}.day-meta{font-size:8px;line-height:1.65;color:#8591a8;margin-top:4px;letter-spacing:.045em}.day-chev{font-size:14px;text-shadow:0 0 12px var(--dc);padding-left:3px}
.start-cta{margin-top:20px;min-height:49px;background:linear-gradient(115deg,#fff645,#fcee0a 75%);box-shadow:0 0 22px #fcee0a38;filter:drop-shadow(0 0 6px #fcee0a2b);font-size:16px;letter-spacing:.1em}
.hint{font-size:10px;color:#8591a8;line-height:1.75}.cta:disabled{opacity:.4;cursor:not-allowed}.ex-sub{color:#8691a6;line-height:1.6}.ex-name{font-size:16px}.lib-main,.si-field{min-width:0}.lib-row{align-items:center;padding:13px 12px;background:linear-gradient(115deg,#101526ee,#0b0e1bee)}.lib-next{font-size:9px;margin-top:6px}.lib-add{flex-shrink:0;min-height:36px}
.filter-row{gap:6px}.chip{min-height:33px;font-size:9px;color:#8f9cb4;padding:7px 9px}.chip.on{background:#fcee0a0b}.search-controls{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(0,1fr);gap:8px;margin:16px 0 12px}.search-controls label{display:block;min-width:0;color:#8290a7;font:8px 'Share Tech Mono',monospace;letter-spacing:.08em}.search-controls input,.search-controls select{display:block;width:100%;min-width:0;height:39px;margin-top:6px;padding:8px;background:#090d19;border:1px solid #00f0ff30;color:#d7e6f4;font:16px 'Rajdhani',sans-serif;border-radius:0;outline:none;transition:border-color .18s,box-shadow .18s}.search-controls input:focus,.search-controls select:focus{border-color:#00f0ff88;box-shadow:0 0 12px #00f0ff18}.search-controls input::placeholder{color:#60728a}.result-count{font:9px 'Share Tech Mono',monospace;color:#00f0ff99;margin:12px 0;letter-spacing:.08em}
.exercise-guide{font:12px/1.65 'Rajdhani',sans-serif;color:#a4b3cc;margin-top:6px}.exercise-guide summary{font:8px 'Share Tech Mono',monospace;letter-spacing:.06em;color:#00f0ff99;cursor:pointer;min-height:27px;display:list-item;align-content:center;width:fit-content}.exercise-guide[open]{padding-bottom:7px}.exercise-guide p{margin:6px 0}.exercise-guide .load-note{color:#c3bd7e}.ex-body .exercise-guide{margin:8px 0}
.ex-card{transition:border-color .2s,box-shadow .2s;background:linear-gradient(110deg,#101426,#0b0d19)}.ex-card.open{box-shadow:inset 0 0 22px #00f0ff06;border-color:#00f0ff70}.ex-head{min-height:67px;gap:8px}.ex-head>div:first-child{min-width:0}.ex-prog{flex-shrink:0}.ex-reveal{display:grid;grid-template-rows:0fr;visibility:hidden;transition:grid-template-rows .28s var(--ease),visibility .28s}.ex-reveal.expanded{grid-template-rows:1fr;visibility:visible}.ex-reveal-inner{overflow:hidden;min-height:0}.ex-body{padding-bottom:15px}.si-field input{min-height:40px}.si-add{min-height:40px}.set-x{min-height:32px;min-width:32px}.sug{font-size:10px}.stat-l,.plan-d,.si-field label,.build-label{color:#8793aa}.stat-card{background:linear-gradient(115deg,#12172a,#0c0f1c)}.stat-n{font-variant-numeric:tabular-nums}.plan-row{gap:12px}.plan-d{flex-shrink:0;align-self:center}.warm-d{font-size:10px}.rest-edit{gap:6px}.rest-step{width:29px;height:29px}.rest-edit-l{color:#7a87a0}.build-row{padding:11px 10px}.tune-gap{margin-left:4px}.build-rm{min-height:32px}.vault-ta{font-size:12px}.vault-msg{line-height:1.6}
.build-row{align-items:flex-start;padding:13px 12px;gap:9px}.build-row .grip{margin-top:6px;padding:5px 5px 5px 0}.build-main>.ex-name{padding-right:27px}.build-rm{position:absolute;right:10px;top:10px;width:27px;height:29px;min-height:0;padding:0;font-size:10px;border-color:#ff003c33}.build-tuning{margin-top:6px}.build-tuning summary{display:flex;justify-content:space-between;align-items:center;cursor:pointer;min-height:29px;font:9px 'Share Tech Mono',monospace;color:#7e90aa;list-style:none}.build-tuning summary::-webkit-details-marker{display:none}.tuning-action{color:#00f0ff;text-shadow:0 0 10px #00f0ff55;padding:6px 8px;border:1px solid #00f0ff25;background:#00f0ff05;font-size:8px}.build-tuning[open] .tuning-action{color:#fcee0a;border-color:#fcee0a40}.tuning-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px 10px;margin-top:12px;padding-top:12px;border-top:1px dashed #ffffff12}.tune-control>span{display:block;font:8px 'Share Tech Mono',monospace;color:#8193ad;margin-bottom:5px}.tune-control>div{display:flex;align-items:center;justify-content:space-between;gap:3px;max-width:135px;background:#080c16}.tune-control button{width:30px;height:32px;flex-shrink:0;background:#00f0ff09;border:1px solid #00f0ff35;color:#00f0ff;font:14px 'Share Tech Mono',monospace;cursor:pointer}.tune-control output{font:12px 'Share Tech Mono',monospace;color:#c5d2e4}.reset-tuning{margin-top:12px;padding:7px 0;background:none;border:none;color:#ff2a6d;font:9px 'Share Tech Mono',monospace;cursor:pointer}
/* The timer and dock occupy real layout space; neither floats across controls. */
.bnav{position:relative;inset:auto;transform:none;width:100%;flex-shrink:0;display:grid;grid-template-columns:repeat(5,minmax(0,1fr));height:calc(65px + env(safe-area-inset-bottom));padding:0 0 env(safe-area-inset-bottom);background:linear-gradient(180deg,#0f1525f7,#090c16);border-top:1px solid #00f0ff35;box-shadow:0 -8px 30px #0007,0 -1px 20px #00f0ff07;isolation:isolate;backdrop-filter:blur(16px);z-index:12}
.bnav-btn{position:relative;flex:none;min-width:0;height:65px;padding:10px 2px 9px;gap:6px;border:0;color:#71819c;font-size:9px;letter-spacing:.08em;transition:color .18s,text-shadow .18s;z-index:1}.bnav-btn.on{border:0;color:#fcee0a;text-shadow:0 0 10px #fcee0a80;background:transparent}.bnav-ic{height:20px;width:20px;display:block;font-size:20px;transition:filter .2s,transform .2s var(--ease)}.bnav-ic svg{display:block;height:100%;width:100%}.bnav-btn.on .bnav-ic{filter:drop-shadow(0 0 5px #fcee0a80);transform:translateY(-1px)}
.nav-indicator{position:absolute;top:0;bottom:env(safe-area-inset-bottom);left:0;width:20%;transform:translateX(calc(var(--nav-index)*100%));background:linear-gradient(180deg,#fcee0a10,transparent 85%);transition:transform .32s var(--ease);pointer-events:none}.nav-indicator::before{content:'';position:absolute;top:-1px;left:18%;right:18%;height:2px;background:#fcee0a;box-shadow:0 0 9px #fcee0a,0 0 20px #fcee0a50}
.rest-bar{position:relative;inset:auto;flex-shrink:0;z-index:11;background:#090f1df5;border-top-color:#00f0ff55;backdrop-filter:none}.rest-inner{width:100%;max-width:none;padding:10px 14px;gap:10px}.rest-ex{font-size:12px}.rest-clock{font-size:23px}.rest-ctrls{gap:5px}.rest-ctrls button{min-height:34px;padding:7px 8px}.rest-label{color:#7789a4}.live-bar{font-size:10px}.flash{top:calc(12px + env(safe-area-inset-top));width:max-content;max-width:min(90vw,550px);font-size:10px;line-height:1.6}
button,a,input,select,textarea,summary{touch-action:manipulation}button{transition:color .15s,border-color .18s,background-color .18s,transform .15s var(--ease),box-shadow .18s}button:active:not(:disabled){transform:translateY(1px) scale(.99)}.bnav-btn:active:not(:disabled){transform:none}.bnav-btn:active .bnav-ic{transform:scale(.87)}summary:focus-visible,select:focus-visible,textarea:focus-visible{outline:2px solid #fcee0a;outline-offset:2px}
@media(hover:hover){.day-card:not(.sel):hover{border-color:color-mix(in srgb,var(--dc) 40%,transparent);background:#141a2c}.bnav-btn:hover{color:#d6dfe9}.chip:not(.on):hover{border-color:#00f0ff66;color:#00f0ff}.lib-add:not(:disabled):hover{background:#fcee0a15}.cta:hover:not(:disabled){filter:brightness(1.08)}}
@media(prefers-reduced-motion:no-preference){.tab-content{animation:panel-in .22s var(--ease) both}.set-row{animation:row-in .2s var(--ease) both}.rest-bar{animation:timer-in .25s var(--ease) both}}
@keyframes panel-in{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:translateY(0)}}
@keyframes row-in{from{opacity:0;transform:translateX(-4px)}to{opacity:1;transform:translateX(0)}}
@keyframes timer-in{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}
@keyframes flashin{from{transform:translate(-50%,-5px);opacity:0}to{transform:translate(-50%,0);opacity:1}}
@media(min-width:680px){.ct-root{border-inline:1px solid #00f0ff15;box-shadow:0 0 80px #00f0ff05,0 0 120px #0008}.hdr{padding-inline:24px}.system-strip{padding-inline:24px}.pad{padding:24px}.day-card{min-height:85px;padding:18px}.day-name{font-size:17px}.day-meta{font-size:9px}.training-readout{margin-bottom:22px}.bnav-btn{font-size:10px}.main{scrollbar-gutter:stable}}
@media(max-width:359px){.hdr{padding-inline:14px;gap:9px}.hdr h1{font-size:24px}.hdr-sub{font-size:7px}.hdr-stat-n{font-size:16px}.hdr-stat-l{font-size:7px}.system-strip{padding-inline:14px;font-size:7px}.pad{padding-inline:12px}.day-card{padding:13px 10px;gap:8px}.day-name{font-size:14px}.day-meta{font-size:7px}.day-letter{font-size:27px}.day-chev{font-size:12px}.bnav-btn{font-size:8px;letter-spacing:.025em}.rest-inner{padding:9px 10px;gap:6px}.rest-clock{min-width:48px;font-size:20px}.rest-ex{max-width:90px}.rest-ctrls button{padding:6px;font-size:10px}.search-controls{grid-template-columns:minmax(0,1.2fr) minmax(0,1fr)}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
`;
